language: objective-c

osx_image: xcode8.2

script:
  - xcodebuild -project "$PROJECT" -scheme 'Metronome' -destination 'name=iPhone 6,OS=10.0' ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build | xcpretty
