language: objective-c

osx_image: xcode8.2

script:
  - xcodebuild -workspace 'Metronome' -scheme 'Metronome' -destination 'name=iPhone 7,OS=10.1' ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build | xcpretty
